listfile = 'E:/Note-/files.txt' # format: string    path/to/file - the string must be unique in the list, it works like a combination of tags + title, and is searchable
pandoc = 'D:/Progra~1/Bulky/Pandoc/pandoc.exe'
te = 'D:/Progra~1/A/EmEditor/EmEditor.exe'
cssjs = 'E:/Note-/style.css'
outfolder = 'E:/Note-/html/' # will generate if not exist
upfolder = '/Note-/'
WinSCP = 'D:/Progra~1/C/WinSCP/winscp.com'
server = 'https://usernameoremail:password@dav.example.com/'
oauth2 = 'youroauth2'
szip = 'D:/Progra~1/T/7Zip/7z.exe'
password = 'yourpassword'
snname = 'youremail'
snpwd = 'yourpassword'
snkeylist = 'E:/Note-/snkey.txt'